name: Test Release Workflow

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --pinentry-mode loopback --import private.key
          rm -f private.key
  
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Check location and correct content settings.xml
        run: cat ~/.m2/settings.xml

      - name: deploy
        run: mvn clean deploy -DskipTests -Prelease
