name: Test Release Workflow

on:
  push:

jobs:
  build:
    runs-on: macos-latest
    steps:

      - name: checkout
        uses: actions/checkout@4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: deploy
        run: mvn clean deploy -DskipTests -Prelease
